### ISSUE TITLE
Documentation overhaul

### ISSUE THREAD

**Issue by marquiz** [intel/cri-resource-manager#175]
We need to go through all the documentation, restructure it and supplement missing areas, before the next release. Motivated by #171 

Backlog (please append new items as you encounter areas to fix):
- [ ] #321 README should provide references to all the sub-documents
- [ ] #320 update RDT documentation, better describing partitions, classes, configuration, exclusivity etc.
- [ ] #121 (Documentation: “how to write policies”)
- [x] #159 (Documentation about how to start cri-resmgr is outdated)
- [ ] #171 (Readme Improvements)
- [ ] #318 document (per policy) handling of isolcpus

**Comment by msivosuo** [comment]
Related issues: #171, #159 , #121

**Comment by marquiz** [comment]
I spent some time on this and decided to use [Github Pages](https://help.github.com/en/github/working-with-github-pages). I think that would allow us much more flexible and easier to navigate documentation.

I did some experimentation with [Hugo](https://gohugo.io/), an easy-to-use static site generator and was quite happy with it. With a minimal effort I was able to create a clean and easily navigable documentation wireframe. It's very nice as you can basically just write markdown files like before. The only overhead is publishing the content, but, even that should be relatively easy to automate with e.g. github workflows (I already created some scripting for that).

You can check out the result on my personal github fork:
https://marquiz.github.io/cri-resource-manager/

My [devel/documentation-overhaul/ghpages](https://github.com/marquiz/cri-resource-manager/tree/devel/documentation-overhaul/ghpages) branch contains the source

WDYT?

**Comment by marquiz** [comment]
My experiment in https://marquiz.github.io/cri-resource-manager/ also (kind-of-implicitly) contains an initial draft of a possible documentation hierarchy/structure. Please comment that, too

**Comment by klihub** [comment]
I have extremely limited experience with this, so this is more of a note than an opinion... I personally ended up using Jekyll for github.io. My unscientific algorithm for choosing that was googling, which gave me the *impression* that
  - Jekyll is the 'natively supported' choice for GitHub pages, and
  - the normal combos seemed to be GitHub pages+Jekyll and Netlify+Hugo

That said, I use Jekyll for occasionally experimenting with a github-based blog and not for a repo-related 'site'. If Hugo is as simple and does everything we need, I'm sure we can use that too.

**Comment by klihub** [comment]
The documentation hierarchy looks like a good staring point. I would consider having the detailed description of policies under Getting Started/Existing Policies, but these kind of stylistic editing is probably best left to the technical writer once we've managed to produce the bulk of the content itself.

**Comment by marquiz** [comment]
> I have extremely limited experience with this, so this is more of a note than an opinion... I personally ended up using Jekyll for github.io.

I think I have even more limited experience in this area 😄 I just ended up experimenting with Hugo before even more deeply thinking about Github Pages integration. I think I'll do a Jekyll experiment, too. That should be really quickly done excercise as I basically have the "content" ready.

**Comment by mythi** [comment]
> probably best left to the technical writer once we've managed to produce the bulk of the content itself.

Let's not forget that they should also be able to provide feedback on the tooling selection and website polishing.

**Comment by klihub** [comment]
@mythi True, but I think in the beginning, when we just need to produce the bulk of the content, what matters the most is that we can get some structure in there and that the tooling does not get too much in the way. Both with Hugo and Jekyll you write markdown, so I think they are both good in this sense.

**Comment by ipuustin** [comment]
@marquiz Not sure if the "Get started/Advanced/Contributing" is a good division -- I guess everyone wanting to try this out needs to somehow be aware of the advanced topics, such as which components there are and how they play together.

Maybe "Get started" should have only a hand-in-hand tutorial for getting cri-rm running and configured and printing CRI requests/responses. Before that there could be an "Introduction" section which explains what cri-rm is, what it does, and what are the most common use cases. Readers could then try to orient first and figure out if cri-rm helps them in what they are trying to do. I guess the largest arch components could be already introduced there.

All the developer stuff (principles, code of conduct, licensing, communication channels, ...) could be under the Contributing part. This is something which could be reflected in the README too.

What do you think?

**Comment by mythi** [comment]
@klihub I agree us focusing on the raw markdown makes sense and that was my point too. We can leave the tooling selection and related meta content to those who help with polishing the docs (IIRC they use Sphinx).

**Comment by mythi** [comment]
FYI: intel/pmem-csi/pull/562

**Comment by marquiz** [comment]
> I guess everyone wanting to try this out needs to somehow be aware of the advanced topics, such as which components there are and how they play together.

That was kind of the idea. Get started would provide a quick start plus a "deep enough" dive in the details in order to get a general good understanding of the project/sw. Advanced would contain defailed "reference manual(s)" and e.g. architecture description which is not essential for daily use.

**Comment by marquiz** [comment]
> I agree us focusing on the raw markdown makes sense and that was my point too. We can leave the tooling selection and related meta content to those who help with polishing the docs (IIRC they use Sphinx).

I think that we should pick the tools/workflow that suits us best. What I would like to see is something very simple and easy to maintain, because in practice, we are going to be the ones who are responsible for maintaining the documentation. I want us to be writing the content, not html templates or css. In that sense I like the hugo experiment above as it's super simple. Just write markdown files and you get well formatted documentation with automatically generated TOC(s) based on the content/structure

**Comment by marquiz** [comment]
> That said, I use Jekyll for occasionally experimenting with a github-based blog and not for a repo-related 'site'

Looking at Jekyll it seems very blog-oriented to me. Automatic/effortless Github integration is VERY nice, though. I'll try and see if I'd find a suitable documentation-oriented theme that would match our needs, for example

**Comment by grahamwhaley** [comment]
ack, I think Jekyll is blog oriented (I used it for a private project once). I struggled with it's macro links - they are not markdown, they are more complex.
If hugo is nice and simple and un-adulterated markdown, then maybe that will work - or, you could just stick with straight github markdown pages (as markdown source in the repo) and wiki pages. Do you need to have a separately generated 'site' would be my first question?

**Comment by marquiz** [comment]
> Do you need to have a separately generated 'site' would be my first question?

That is a good question. I think that would make it easy to have easy-to-access versioned documentation for releases. I think it will also make the maintenance easier as documentation we can require a doc update (if applicable) on each PR. For these reasons I wouldn't use wiki. Plain markdown files work, of course, but we lose the user-friendliness.

**Comment by grahamwhaley** [comment]
ack. I think the 'one place' for docs and the searchability would be great additions.
If you can also have versioned docs via whatever method you use, that would also be great.
All three of those are things we struggle with over in the land of [Kata Containers](https://github.com/kata-containers), where we predominantly use the vanilla in-source github markdown file method.

We do however have a markdown [doc check CI](https://github.com/kata-containers/tests/tree/master/cmd/check-markdown) that also incorporates a [spell checker](https://github.com/kata-containers/tests/tree/master/cmd/check-spelling) that you could leverage if you go there :-) If you get to that point, feel free to ask for some info on how it is structured etc.

**Comment by klihub** [comment]
If I could name *just one* thing I'd really like to have then I couldn't pick it... But if I was allowed to name *two* things, then those would be:
  1. the same  workflow for documentation as for code (AMAP, ideally identical)
  2. the ability to easily preview locally on my own machine a documentation change

With 1 keeping the docs up-to-date could/would become an integral part of the normal day-to-day workflow instead of being an afterthought. Related to 2 above... I also want to be able to do that *without* having to install something which is not widely used out there.

**Comment by marquiz** [comment]
@klihub I fully agree 👍  I think you listed those in my personal priority order 😄 

I think the workflow should be identical. The second one should be relatively straightforward to achieve with some dockerization, at least

**Comment by grahamwhaley** [comment]
just fyi, I use https://github.com/joeyespo/grip to review github markdown locally - works well enough. Easier than pushing it up to a personal branch to review on github itself.

**Comment by marquiz** [comment]
I now have a sort of working prototypes of both the Hugo and Jekyll implementations.
1. Hugo
Code on the [devel/documentation-overhaul/hugo](https://github.com/marquiz/cri-resource-manager/tree/devel/documentation-overhaul/hugo) branch
Wireframe example site at https://marquiz.github.io/cri-resource-manager/hugo/
2. Jekyll 
Code on the [devel/documentation-overhaul/jekyll](https://github.com/marquiz/cri-resource-manager/tree/devel/documentation-overhaul/jekyll) branch
Wireframe example site at https://marquiz.github.io/cri-resource-manager/jekyll/

Both use an MIT-licensed 3rd party theme ([Book](https://github.com/alex-shpak/hugo-book) with Hugo and [Just the Docs](https://github.com/pmarsceill/just-the-docs) with Jekyll) for simple documentation-oriented layout.

Both now have a containerized solution for doing documentation builds and viewing it locally, meaning that no extra dependencies (except for docker) are required for working with documentation.
```make site-build``` builds the documentation
```make site-serve``` builds and serves the documentation (at [localhost:4000/](http://localhost:4000/) with Jekyll and at [localhost:1313/cri-resource-manager/](http://localhost:1313/cri-resource-manager/) with Hugo)

Both solutions also have Github Pages integration. With Jekyll that means nothing (nice!) as it's natively supported by Github. With Hugo that is done through Github Actions, now implemented as a separate relatively simple workflow, augmented by one makefile rule and a script for updating the gh-pages git branch.

Comments and thoughts would be appreciated.

What I like in the Hugo solution is the simplicity from the documentation-writer's point-of-view. Right and left side navigation (site TOC and page TOC) are automatically generated based on the file/directory structure. Less extra/boilerplate in the markdown files. What I like in Jekyll is the automatic Github integration.

**Comment by klihub** [comment]
To me both of those look fine with the necessary makefile rules in place to help with day-to-day workflows. Both of the generated outputs look fine as well. At this point I'm happy with whichever we end up using. Besides, I think we anyway need to pick one and start using it to be able to form a quantified opinion about how well it works and if there are any pain points.

If I had to forcibly come up with some comments based on just skimming through your sample branches, then those could be that I'm positively surprised that Jekyll has native remote theme support (I had no idea) and that I slightly dislike the fact that the Hugo way for the same seems to be forcing git submodule usage. But both of these are insignificant minor noise in the bigger scheme of things.

**Comment by msivosuo** [comment]
Split to specific sub-tasks. This one can be closed one sphinx-based documentation becomes available.

**Comment by msivosuo** [comment]
https://intel.github.io/cri-resource-manager/README.html

**Comment by klihub** [comment]
And even this URL should be enough, it redirects to README.html: https://intel.github.io/cri-resource-manager
