### ISSUE TITLE
Original TODO.md as an issue

### ISSUE THREAD

**Issue by klihub** [intel/cri-resource-manager#301]
This is the content from our unmaintained TODO.md converted to an issue, with the most obviously outdated items removed. Feel free to update, split out to separate, issues, etc. as necessary.

## Static Pools
- [ ] helper tool for creating configuration (á la `cmk init`)

### Multiple Active Policies
- [ ] cache: add support for saving data for multiple policies
- [ ] policy: pick policy for container creation requests

### Policy:
- [ ] define/pass explicitly interfaces for commonly needed functionality to policies,
at least for
  -  [ ] system introspection (sysfs, topology, etc.)

## Cleanups
- [ ] needed all over the place

## Testing
- [ ] needed all over the place, only `static-pools` has test cases
- [ ] end goal is to be able to automatically test the policy decision making
in complete isolation by feeding synthetic requests and checking the resulting
decisions/actions are as expected

**Comment by msivosuo** [comment]
subset of #360, closing.
